version: '3.7'

networks:
  logging:
    name: logging
    driver: overlay
    attachable: true

services:
  web:
    image: httpd
    ports:
      - "80:80"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: fluentd:24224
        tag: httpd.access
    networks:
      - logging

  fluentd:
    image: pjoisha/fluentd-base
    volumes:
      - ./fluentd/conf:/fluentd/etc
    deploy:
      mode: global
    networks:
      - logging

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    networks:
      - logging

  kibana:
    image: kibana:7.2.0
    ports:
      - "5601:5601"
    networks:
      - logging
